version: '3'
 
services:
    web1:
        image: dockercloud/hello-world
        ports:
            - "81:80"

    web2:
        image: dockercloud/hello-world
        ports:
            - "82:80"
        
    haproxy:
        container_name: haproxy
        build: ./haproxy
        ports:
            - 80:80